CREATE SCHEMA IF NOT EXISTS videoStore;

CREATE TABLE IF NOT EXISTS movies (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(300) NOT NULL,
	director VARCHAR(200) NOT NULL,
	quantity INT
);

CREATE TABLE IF NOT EXISTS users (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(300) NOT NULL,
	email VARCHAR(200) NOT NULL,
	password VARCHAR(200) NOT NULL,
	CONSTRAINT UK_User_Email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS rentMovies (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	movieId BIGINT NOT NULL,
	userId BIGINT NOT NULL,
	CONSTRAINT FK_RentMovies_Movies FOREIGN KEY (movieId) REFERENCES movies(Id),
	CONSTRAINT FK_RentMovies_User FOREIGN KEY (userId) REFERENCES users(Id),
	CONSTRAINT UK_Rent UNIQUE (movieId, userId)
);